---
HOSTS:
  el8:
    roles:
    - directory_server
    - default
    platform: el-8-x86_64
    box: generic/centos8
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    family: centos-cloud/centos-stream-8
    gce_machine_type: n1-standard-2
  client-el8:
    roles:
    - client
    platform: el-8-x86_64
    box: generic/centos8
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    family: centos-cloud/centos-stream-8
    gce_machine_type: n1-standard-2
  client-el7:
    roles:
    - client
    platform: el-7-x86_64
    box: centos/7
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    family: centos-cloud/centos-7
    gce_machine_type: n1-standard-2
CONFIG:
  log_level: verbose
  type: aio
  vagrant_memsize: 512
  vagrant_cpus: 1
  puppet_collection: "<%= ENV.fetch('BEAKER_PUPPET_COLLECTION', 'puppet7') %>"
